# Generated by Django 5.2.8 on 2025-11-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inamrestroapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
