# Generated by Django 5.2.8 on 2025-11-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inamrestroapp', '0002_loin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loin',
        ),
    ]
